### ISSUE TITLE
Add DNS Support for domain name

### ISSUE THREAD

**Issue by MaxAsif** [nexus-lab-org/port-sniffer#1]
Overall Idea, is to be able to use domain name and find the ports available.

**Comment by MaxAsif** [comment]
We can use std library `net` [link](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html#examples) to get this

**Comment by rootCircle** [comment]
Hey! I would love to work on this! I am thinking of implementing [dns_lookup](https://docs.rs/dns-lookup/latest/dns_lookup/) for this feature.
