### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by MaxAsif** [nexus-lab-org/port-sniffer#16]
* Add all the flags option with default value 
* Add contributors section
* Add a section for contributing guidelines

**Comment by khushalmajoka** [comment]
Hi @MaxAsif,
Can you please explain the pointers more precisely, what does you want actually?

**Comment by MaxAsif** [comment]
We have added few more options in the tool. We can add it in the README. Also we can add a contributing guidelines docs and a section to display the contributors using this [link](https://contrib.rocks/image?repo=nexus-lab-org/port-sniffer)
```sh
A port sniffer written in Rust

Usage: nexuslab_port_sniffer [OPTIONS]

Options:
  -i, --ip <IP>            IP address
  -t, --threads <THREADS>  Number of threads [default: 10]
      --domain <DOMAIN>    Domain name
      --timeout <TIMEOUT>  Expected Timeout over each TCP connect [default: 2]
      --ports <PORTS>...   Ports to be scanned (optional, if unspecified, all ports will be scanned)
  -h, --help               Print help
  -V, --version            Print version
```

**Comment by kunjshukla** [comment]
Hey there, can you please assign me this issue.

**Comment by MaxAsif** [comment]
Closing with PR #28
