### ISSUE TITLE
Improve the UX in CLI

### ISSUE THREAD

**Issue by MaxAsif** [nexus-lab-org/port-sniffer#18]
* Handle SIGINT/SIGSTOP signal and display the result of ports scanned till the signal
* Show the progress of ports that have been scanned.

**Comment by 0Ky** [comment]
Hello! I'm currently working on this issue https://github.com/0Ky/port-sniffer/commit/fad7f7873b9faa52d36799d4324e6a7e0306a865.

**Comment by MaxAsif** [comment]
Fix with PR #25
