### ISSUE TITLE
Unexpected Behaviour

### ISSUE THREAD

**Issue by sathuhebbar** [nexus-lab-org/port-sniffer#20]
Observed the following issues with the latest iteration of the code on master:

![image](https://github.com/nexus-lab-org/port-sniffer/assets/35398441/eff45e79-27b3-41e3-94c5-f006f0c687ca)

Other observed issues:
1. Only one input range is being analysed even when multiple are given. 
2. Ranges and individual ports cannot be mixed.

**Comment by 0Ky** [comment]
When using the `--ports` argument in the tool, the specified port range seems to be interpreted as half-open. This means that while it starts scanning from the specified beginning port, it stops just before the ending port. For example, inputting `--ports 100-200` scans ports from `100` through `199`, but it unexpectedly leaves out port `200`.

**Comment by MaxAsif** [comment]
Fix it with #22
