### ISSUE TITLE
Not scanning multiple ports

### ISSUE THREAD

**Issue by sathuhebbar** [nexus-lab-org/port-sniffer#24]
The previous issue persists:
![image](https://github.com/nexus-lab-org/port-sniffer/assets/35398441/aa51bf38-70dd-43f6-8830-1bc7abdf21b9)

**Comment by sathuhebbar** [comment]
Can I work on fixing this issue while adding support for mixing port ranges and individual ports?

I think the issue here is that each port/range gets passed to `from_str` due to `num_args=1..`, and clap is not unifying the results from each `from_str` properly.

Thanks.

**Comment by MaxAsif** [comment]
Closing with: PR #26
