### ISSUE TITLE
Add timeout to TCP Connect

### ISSUE THREAD

**Issue by MaxAsif** [nexus-lab-org/port-sniffer#3]
If an IP is not accessible, add a timeout of 2 sec.

**Comment by rootCircle** [comment]
Hey! I would love to work on this! 

I am expecting that this might work as expected, plus we could pass in duration as an cli argument, maybe?
```
-        match TcpStream::connect(address) {
+       match TcpStream::connect_timeout(&socket_add, duration) {
```

**Comment by MaxAsif** [comment]
Yes, that should work. 
We can add this as an argument, with some default value.
