### ISSUE TITLE
Scan for specific port

### ISSUE THREAD

**Issue by MaxAsif** [nexus-lab-org/port-sniffer#9]
A feature to specify certain ports to scan for or a single port to check

**Comment by sathuhebbar** [comment]
Hey, I'm new to Rust, but can I try taking up this task?

Thank you.

**Comment by MaxAsif** [comment]
Sure, go ahead.

**Comment by sathuhebbar** [comment]
Thanks a lot. If I have any queries can I ask them here, or is there some other communication platform that I should use?

**Comment by MaxAsif** [comment]
You can ask here.

**Comment by sathuhebbar** [comment]
I have tried implementing it. How should I add my changes to the repo? I am unable to create a branch as it says it is not permitted. Should I fork the repository and make the changes there?

Thank you.

**Comment by sathuhebbar** [comment]
I've made changes to the fork and I've created a PR. Please have a look.
Thanks!
